version: '3'

volumes:
  postgres:
    driver: local

services:
  postgres:
    image: postgres:10
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: CarShowroomDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
#
#  api:
#    image: localhost:6000/car-showroom-api
#    ports:
#      - 5000:80
#    build:
#      context: ./
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    restart: always
#    links:
#      - postgres
