// <auto-generated />
using System;
using CarShowroom.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CarShowroom.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CarShowroom.Database.Models.Car", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AutomaticTransmission");

                    b.Property<string>("Brand");

                    b.Property<string>("Client");

                    b.Property<string>("Color");

                    b.Property<bool>("Conditioner");

                    b.Property<bool>("CruiseControl");

                    b.Property<int>("DoorsNumber");

                    b.Property<float>("EnginePower");

                    b.Property<float>("EngineVolume");

                    b.Property<string>("Fuel");

                    b.Property<float>("FuelConsumption");

                    b.Property<bool>("GpsNavigator");

                    b.Property<string>("Interior");

                    b.Property<string>("Manufacturer");

                    b.Property<string>("Milage");

                    b.Property<string>("Price");

                    b.Property<bool>("Radio");

                    b.Property<string>("RegistryNumber");

                    b.Property<int>("SeatsNumber");

                    b.Property<DateTime>("TO");

                    b.Property<bool>("Video");

                    b.Property<int>("VolumeTrunk");

                    b.HasKey("Guid");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarShowroom.Database.Models.Client", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<string>("Phone");

                    b.HasKey("Guid");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CarShowroom.Database.Models.Order", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("Client");

                    b.Property<Guid?>("ClientGuid");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Status");

                    b.Property<bool>("TestDrive");

                    b.HasKey("Guid");

                    b.HasIndex("ClientGuid");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CarShowroom.Database.Models.Order", b =>
                {
                    b.HasOne("CarShowroom.Database.Models.Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientGuid");
                });
#pragma warning restore 612, 618
        }
    }
}
